### ISSUE TITLE
library order is wrong for ubuntu

### ISSUE THREAD

**Issue by bjoring** [melizalab/aplot#1] opened 2018-06-22 15:36 UTC
During the final link step, on ubuntu xenial, the linker will have a cow if -ldataio comes after -ljpeg. Not sure if rearranging this will break linkage on other systems, so just posting as an issue.

**Comment by dmeliza** [comment] 2024-02-12 15:11
Closing as I am not sure how to reproduce this.

**Comment by dmeliza** [comment] 2024-02-12 15:14
Reopening this as this seems to be the underlying issue with a new error on Debian 12. With the default order of libraries, the linker fails with the following error:

```
gcc -o src/aplot src/aplot.o src/aplot_ui.o src/aplot_panel.o src/aplot_misc.o src/xm_attach.o src/aplot_label.o src/aplot_rast.o src/aplot_psth.o src/aplot_isi.o src/aplot_ccor.o src/aplot_osc.o src/aplot_sono.o src/aplot_psip.o src/aplot_postscript.o src/aplot_spectrum.o src/aplot_video.o src/aplot_defaults.o src/aplot_x11.o src/XCC.o src/colormap.o -L/usr/lib/x86_64-linux-gnu/hdf5/serial -Llibsono -Llibdataio -lm -lfftw3 -lXm -lXmu -lXt -lSM -lICE -lXext -lXft -lfontconfig -lXrender -lX11 -lfreetype -lxcb -lXau -lXdmcp -lhdf5 -ljpeg -lsono -ldataio

/usr/bin/ld: libdataio/libdataio.a(vidavi.o): undefined reference to symbol 'jpeg_mem_src@@LIBJPEGTURBO_6.2'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/libjpeg.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Switching the order around to the following works without error:

```
gcc -o src/aplot src/aplot.o src/aplot_ui.o src/aplot_panel.o src/aplot_misc.o src/xm_attach.o src/aplot_label.o src/aplot_rast.o src/aplot_psth.o src/aplot_isi.o src/aplot_ccor.o src/aplot_osc.o src/aplot_sono.o src/aplot_psip.o src/aplot_postscript.o src/aplot_spectrum.o src/aplot_video.o src/aplot_defaults.o src/aplot_x11.o src/XCC.o src/colormap.o -L/usr/lib/x86_64-linux-gnu/hdf5/serial -Llibsono -Llibdataio -lm -lfftw3 -lXm -lXmu -lXt -lSM -lICE -lXext -lXft -lfontconfig -lXrender -lX11 -lfreetype -lxcb -lXau -lXdmcp -ldataio -ljpeg -lsono -lhdf5
```

**Comment by dmeliza** [comment] 2024-02-12 15:54
This is fixed now. I'm just compiling everything into the program rather than having the intermediate step of creating a library.

**Closed as completed by dmeliza** 2024-02-12 15:54 UTC
Labels: bug
